blank_issues_enabled: false
contact_links:
  - name: ğŸ’… Feature Request - Ideas
    url: https://feedback.nanos.world/
    about: Use our new platform to collect feedback and ideas, vote for the best and suggest new ones!

  - name: â“ Simple question - Discord Chat
    url: https://discord.nanos.world/
    about: Feel free to reach us to debate on Discord!
